[connections.snowpark]
account = "DNIFRBJ-LO80179"
user = "MARYAMILYAS"
password = "YVkeunb4wkjk"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "EMISSION_FACTORS_DATABASES"
schema = "PUBLIC"
client_session_keep_alive = true
